### ISSUE TITLE
[Reusable Workflow] Create a reusable workflows for Download Artifact & Repo Setup

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#844]
## Description

Now that we have researched the benefits of reusable workflows we want to test this out on some higher priority items. We will create these at the repo level for now, and in the future discuss what workflows would benefit from living at the Org level.
See some additional details on the benefits [here](https://github.com/newrelic/docs-website/issues/5078#issuecomment-1039305342).

<details><summary>Download Artifact Code</summary>

```
- name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "::set-output name=pr-number::$PR_NUMBER"
```

</details>

We use `Download Artifact` in: 
 - [pr-merged.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/pr-merged.yml)
 - [validate_install_plans.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_install_plans.yml)
 - [validate_packs.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)

<details><summary>Setup Repo Code</summary>

```
- name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          ref: "main"
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd utils && yarn install
```

</details>

We use `Download Artifact` in: 
 - [pr-merged.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/pr-merged.yml)
 - [validate_install_plans.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_install_plans.yml)
 - [validate_packs.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)
 - [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/release.yml)
 - [run_tests.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/run_tests.yml)

See instructions on how to create a Reusable Workflow [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows)

## Acceptance Criteria

 - [ ] Create a reusable workflow for Download Artifact 
 - [ ] Create a reusable workflow for Setup Repo
 - [ ] Replace these jobs in the relevant workflows
 - [ ] Record any issues or pitfalls for future work
