### ISSUE TITLE
[Repository] Quickstart install plan name and title should be sentence case

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#919]
As part of the quality bug bash an internal JIRA ticket was reported `JIRA` `DEVEX-2284` pointing to the [Python agent ](https://github.com/newrelic/newrelic-quickstarts/blob/main/install/apm/python/install.yml#L2-L3) quickstart which has a title and name field with camel casing. New Relic's standard is to use sentence casing, so we should go through the repo and programmatically check for quickstarts that aren't cased correctly.

### Casing rules to consider 

- New Relic `agent` is lower case.
-  `SDK` is all caps
- the word `installation` is lower case if it is not the first word
-  `AWS` products are camel case e.g;  `AWS Lambda` , `AWS Infrastructure` is camel case
-  `Azure` products are camel case e.g;  `Azure Infrastructure` is camel case
- `Gatsby Build` is camel case
-  `Truera Diagnostics & Monitoring` is camel case
- `Mona Labs` is camel case
-  `DagHub` is camel case
-  `Aporia Model Observability & Monitoring Platform`
-  There are other nuances that required me to look up product documentation to confirm the right casing.

```yaml 

id: setup-python-agent
name: Python Agent
title: Python Agent Installation
description: Start monitoring the performance of a Python application or service by installing the New Relic Python agent.
```

**Change to**

```yaml 

id: setup-python-agent
name: Python agent
title: Python agent installation
description: Start monitoring the performance of a Python application or service by installing the New Relic Python agent.
```

### Screenshot

<img width="974" alt="Screen Shot 2022-03-21 at 11 58 39 AM" src="https://user-images.githubusercontent.com/1395158/159335456-fa075d8f-524a-4e78-8352-c4eb062004a8.png">

### Acceptance Criteria 

- [ ] programmatically change all camel case names and titles to sentence case
- [ ] confirm this is resolved in `JIRA` `DEVEX-2284` and close the ticket
